### ISSUE TITLE
Update to TLS 1.2

### ISSUE THREAD

**Issue by tulbox** [bambora-na/bambora-na-dotnet#25]
According to https://help.na.bambora.com/hc/en-us/articles/115015460087-TLS-Upgrade-TLS-1-2, support for TLS 1.0 and 1.1 will be removed as of April 30, 2018. However, the "Update to TLS 1.2" commit includes mass namespace/branding changes (not just the TLS 1.2 update changes). Sigh. There's no quick way to see what "PAY-1936 SDK updated to support TLS1.2" really entails (see https://github.com/bambora-na/bambora-na-dotnet/commit/30e8d4a2a1625cfc73a3b4a8523d2328773bc829). Therefore, we have to dig through it all to find out if switching over to bambora-na-dotnet v2.0 from Beanstream v1.2 is adequate to comply with the upcoming TLS 1.2 requirements:

> In order to verify that you've fully deprecated TLS 1.0 and 1.1 we have created a separate TLS 1.2 only endpoint for you to use for confirmation.
> 
> This is a production endpoint so we advise you test your integration in the following way:
> 
> 1. Point your staging environment towards the following domain: https://tls12-api.na.bambora.com (as opposed to ‘https://api.na.bambora.com’)
> 2. Process at least one attempt of all requests to each different endpoint (Payments, Profiles, Reporting etc) that your integration to Bambora includes.
> 3. If the requests are successful use your normal Bambora credentials and log in to the TLS 1.2 only backoffice at: https://tls12-web.na.bambora.com/admin/sDefault.asp and confirm that the transactions shows up as expected.

Short of recompiling the SDK after overriding the BaseUrl specified in https://github.com/bambora-na/bambora-na-dotnet/blob/942163384053fcf6babfac9eff70fd688125662c/BamboraSDK/BamboraUrls.cs, is there an undocumented means of following your recommended testing (point at https://tls12-api.na.bambora.com)?

Alternatively, can we have *official confirmation* that upgrading to this Bambora v2.0 SDK will cover every TLS 1.2 requirement (no nasty surprises on April 30)?

**Comment by regexen** [comment]
Adding in to this : I'm slightly concerned about the way TLS 1.2 support is enabled in <https://github.com/bambora-na/bambora-na-dotnet/blob/942163384053fcf6babfac9eff70fd688125662c/BamboraSDK/Data/WebCommandExecuter.cs>; that is, by directly setting `System.Net.ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12`.

As far as I can tell, that setting affects the whole AppDomain; possibly breaking support for other requests that target servers which only support say, TLS 1.0, for instance.

Since this is a `[Flags]` enum, would it not be better to check if TLS 1.2 support is there, and add it to the set of supported protocols if not ? I've tested it against the TLS 1.2-only endpoint and it seems to work. If that solution works for everyone, I can submit a pull request.

**Comment by draganblagojevic** [comment]
@tulbox 
Yes, using Bambora SDK v2.0 will give you full TLS 1.2 support for integrating with Bambora API.

**Comment by draganblagojevic** [comment]
@regexen 
thanks for feedback, we will add support for Tls 1.1 and 1.0, update should be out by the end of the week

**Comment by tulbox** [comment]
@draganblagojevic @regexen It is now April 26, 2018, and no "we will add support for Tls 1.1 and 1.0, update should be out by the end of the week".  See https://github.com/bambora-na/bambora-na-dotnet/pull/26 still outstanding.

**Comment by draganblagojevic** [comment]
Fixed as of version 2.1.0
